version: '2'

services:
  app:
    build: ../../node-hello-world

  proxy:
    build: ../../nginx-proxy
    depends_on:
      - app
    environment:
      BACKEND: app
    ports:
      - 5678:80

  client:
    build: ../../ubuntu-with-curl
    depends_on:
      - proxy
    command: sh -c "while true; do curl http://proxy; sleep 1; done"
